filters:
  - filter_type: file
    file_format: KEYVALUEJSON
    source_language: en
    source_file: src/tr-web-control/i18n/en.json
    translation_files_expression: 'src/tr-web-control/i18n/<lang>.json'
