name: 'Setup Node and run npm ci'
description: 'setup node env'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'

    - run: corepack enable
      shell: bash

    - run: corepack prepare --activate
      shell: bash

    - run: pnpm --version
      shell: bash

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: pnpm i --frozen-lockfile
      shell: bash
