name: CI

on:
  pull_request:
    branches:
      - 'master'

  push:
    branches:
      - 'master'
      - '!renovate/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-env

      - run: npx prettier --check ./

      - run: npx tsc

      - run: pnpm test --coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-env

      - run: npx prettier --check ./

      - run: npx tsc

      - run: pnpm lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-env

      - run: pnpm build

      - run: zip -r dist.zip ./dist/
      - run: tar -czvf dist.tar.gz ./dist/

      - uses: actions/upload-artifact@v3
        with:
          name: build-tar
          path: dist.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: build-zip
          path: dist.zip
