name: Pull Transifex

on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 4 * * 4'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir -p ~/.local/bin
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
          mv ./tx ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - run: tx pull --mode onlytranslated --all --use-git-timestamps
        env:
          TX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}

      - uses: ./.github/actions/setup-js-env

      - run: node ./.github/scripts/remove-empty-string.mjs
      - run: pnpm format

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          title: 'chore: sync transifex translation'
          branch: 'chore/i18n-pull'
          author: 'Trim21 <trim21.me@gmail.com>'
